### ISSUE TITLE
[feature]: `reqwest` backend

### ISSUE THREAD

**Issue by tazz4843** [flying7eleven/fenrir-rs#1]
### What's your idea?

I found this crate, and it seems like exactly what I need for my project. However, I currently do not pull in `ureq` in my project and I'd prefer not to do so. I would be willing to make a PR to add a `reqwest` feature if that's something you'd be interested in.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by flying7eleven** [comment]
Hey ☺️ To be honest, that would be quite grate! Currently, I have not enough time to spare to implement the `reqwest` backend myself but it was planned anyways. So I would really appreciate your help for that!

<edit>I also finally added a [styleguide](https://github.com/flying7eleven/fenrir-rs/blob/main/STYLEGUIDE.md) to the repository to make it easier for potential contributors.</edit>
